# Generated by Django 3.1.1 on 2020-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='производитель')),
                ('model', models.CharField(max_length=200, verbose_name='модель авто')),
                ('year_start', models.IntegerField(verbose_name='год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], verbose_name='коробка передач')),
                ('color', models.CharField(max_length=100, verbose_name='цвет')),
            ],
        ),
    ]
